spring:
  application:
    name: api-widgets
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  flyway:
    password: ${DB_USERNAME}
    user: ${DB_USERNAME}

debug: true